<%@ page import="java.util.ArrayList" %>
<%@ page import="objects.questions.Question" %>
<%@ page import="java.util.List" %>
<%@ page import="java.util.Arrays" %>
<%List<Question> questions = (ArrayList<Question>)request.getAttribute("questions");%>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <title>Editing Quiz</title>
</head>
<body>
<h1>Questions: </h1>
<%
    if (questions.isEmpty()) {
        out.println("<h2>The quiz is empty</h2>");
    }
%>
<%
    int i = 1;
    for (Question question : questions) {
        out.println("<h2>" + i + ") " + question.getQuestionType() + "</h2>");
        if (question.getQuestionType().equals("AutoGeneratedQuestion")) {
            i++;
            continue;
        }
%>
<div class="question">
    <p class="questionText">
        <%
            if (question.getQuestionType().equals("PictureResponse")) {
                out.println("<img src=\"" + question.getQuestion() + "\" alt=\"Description of the image\" width=\"300\" height=\"200\" id=\"questionImage\">");
            } else {
                out.println("<p id=\"questionText\">Question text: " + question.getQuestion() + "</p>");
            }
        %>
    </p>
    <p class="questionOptions">
        <ul>
            <%
                if (Arrays.asList("MultipleChoice", "MultipleChoiceWithMultipleAnswer").contains(question.getQuestionType())) {
                    out.println("Possible options:");
                    for (String choice : question.getOptions()) {
                        out.print("<li>");
                        out.print(choice);
                        out.print("</li>");
                    }
                }
            %>
        </ul>
    </p>
</div>

<%
        i++;
    }
%>
</body>
</html>
