<%@ page import="java.util.ArrayList" %>
<%@ page import="objects.questions.Question" %>
<%@ page import="java.util.List" %>
<%@ page import="java.util.Arrays" %>
<%List<Question> questions = (ArrayList<Question>)request.getAttribute("questions");%>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="css/editQuiz.css"></head>
<title>Editing Quiz</title>
</head>
<body>
<h1>Questions: </h1>
<%
    if (questions.isEmpty()) {
        out.println("<h2>The quiz is empty</h2>");
    }
%>
<div class="add-question">
    <form action="addQuestion?quizId=<%=request.getParameter("quizId")%>" method="POST">
        <label for="questionType">Select Question Type To Add: </label>
        <select id="questionType" name="questionType">
            <option value="QuestionResponse">Question Response</option>
            <option value="FillInTheBlank">Fill In The Blank</option>
            <option value="PictureResponse">Picture Response</option>
            <option value="MultipleChoice">Multiple Choice</option>
            <option value="MultipleChoiceWithMultipleAnswer">Multiple Choice With Multiple Answer</option>
            <option value="MultiAnswer">Multi Answer</option>
            <option value="Matching">Matching</option>
            <option value="AutoGeneratedQuestion">Auto Generated Question</option>
        </select>
        <input type="submit" value="Add">
    </form>
</div>


<%
    int i = 1;
    for (Question question : questions) {
        out.println("<h2>" + i + ") " + question.getQuestionType() + "</h2>");
        if (question.getQuestionType().equals("AutoGeneratedQuestion")) {
            i++;
            continue;
        }
        %>
        <div class="question">
            <div class="questionText">
                <%
                    out.println("<p id=\"questionText\">Question text: " + question.getQuestion() + "</p>");
                    if (question.getQuestionType().equals("PictureResponse")) {
                        out.println("<img src=\"" + question.getOptions()[0] + "\" alt=\"Description of the image\" width=\"300\" height=\"200\" id=\"questionImage\">");
                    }
                %>
            </div>
            <div class="questionOptions">
                <ul>
                    <%
                        if (Arrays.asList("MultipleChoice", "MultipleChoiceWithMultipleAnswer").contains(question.getQuestionType())) {
                            out.println("Possible options:");
                            for (String choice : question.getOptions()) {
                                out.print("<li>");
                                out.print(choice);
                                out.print("</li>");
                            }
                        }
                    %>
                </ul>
            </div>

            <div class="matching-container">
                    <%
                        if (question.getQuestionType().equals("Matching")) {
                            out.println("<div class=\"side\" id=\"leftSide\">");
                            out.println("<h2>Left Side</h2>");
                            out.println("<ul>");
                            for (String leftItem : question.getOptions()) {
                               out.print("<li>" + leftItem + "</li>");
                            }
                            out.println("</ul>");
                            out.println("</div>");

                            out.println("<div class=\"side\" id=\"rightSide\">");
                            out.println("<h2>Right Side</h2>");
                            out.println("<ul>");
                            for (String rightItem : question.getCorrectAnswers()) {
                                out.print("<li>" + rightItem + "</li>");
                            }
                            out.println("</ul>");
                            out.println("</div>");
                        }
                    %>
            </div>

            <% int timer = question.getTimer(); %>
            <p class="<%= timer == 0 ? "no-timer" : "timer" %>">
                <%= timer == 0 ? "This question doesn't have a timer." : "Time for this question: " + timer + " seconds."%>
            </p>


        </div>
        <div class="removeQuestion">
            <form action="removeQuestion?quizId=<%=request.getParameter("quizId")%>" method="post">
                <input type="hidden" name="questionId" value="<%=question.getQuestionId()%>">
                <input type="submit" value="Remove this question">
            </form>
        </div>
        <%
        i++;
    }
%>
</body>
</html>
