<%@ page import="java.util.ArrayList" %>
<%@ page import="objects.questions.Question" %>
<%@ page import="java.util.List" %>
<%@ page import="java.util.Arrays" %>
<%@ page import="dataBase.DbQuizDAO" %>

<%
    List<Question> questions = (ArrayList<Question>)request.getAttribute("questions");
    String quizId = request.getParameter("quizId");
%>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="css/editQuiz.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>Editing Quiz</title>
</head>

<body>
<div class="add-question-page">
    <h1> create quiz </h1>
    <div class="add-question">
        <form action="addQuestion?quizId=<%=quizId%>" method="POST">
            <label for="questionType">Select Question Type To Add: </label>
            <select id="questionType" name="questionType">
                <option value="QuestionResponse">Question Response</option>
                <option value="FillInTheBlank">Fill In The Blank</option>
                <option value="PictureResponse">Picture Response</option>
                <option value="MultipleChoice">Multiple Choice</option>
                <option value="AutoGeneratedQuestion">Multiple Choice (Auto Generated)</option>
                <option value="MultipleChoiceWithMultipleAnswer">Multiple Choice With Multiple Answer</option>
                <option value="MultiAnswer">Multi Answer</option>
                <option value="Matching">Matching</option>
                <option value="Graded">Graded</option>
            </select>
            <input type="submit" value="Add">
        </form>
    </div>
    <%
        int i = 1;
        for (Question question : questions) {
            String questionType = question.getQuestionType();
            if ("AutoGeneratedQuestion".equals(questionType)) {continue;}
    %>
    <div class="question">
        <h2><%= i++ %>. <%= questionType %></h2>


        <div class="questionText">
            <p id="questionText">Question text: <%= question.getQuestion() %></p>
            <% if ("PictureResponse".equals(questionType)) { %>
                <img src="<%= question.getOptions()[0] %>" alt="Description of the image" width="100" height="100" id="questionImage">
            <% } %>
        </div>

        <% if (Arrays.asList("MultipleChoice", "MultipleChoiceWithMultipleAnswer").contains(questionType)) { %>

            <div class="questionOptions">
                <% for (String choice : question.getOptions()) { %>
                    <p class="choice"><%= choice %></p>
                <% } %>
            </div>
        <% } %>

        <% if ("Matching".equals(questionType)) { %>
            <div class="matching-container">
                <div class="side" id="leftSide">
                    <div>
                        <% for (String leftItem : question.getOptions()) { %>
                        <p class="choice"><%= leftItem %></p>
                        <% } %>
                    </div>
                </div>
                <div class="side" id="rightSide">
                    <div>
                        <% for (String rightItem : question.getCorrectAnswers()) { %>
                        <p class="choice"><%= rightItem %></p>
                        <% } %>
                    </div>
                </div>
            </div>
        <% } %>

        <p class="<%= question.getTimer() == 0 ? "no-timer" : "timer" %>" style="font-size: 10px; color: darkgray;">
            <%= question.getTimer() == 0 ? "This question doesn't have a timer." : "Time for this question: " + question.getTimer() + " seconds." %>
        </p>

        <form action="removeQuestion" method="POST">
            <input name="quizId" value="<%=request.getParameter("quizId")%>" type="hidden">
            <input type="hidden" name="questionId" value="<%= question.getQuestionId() %>">
            <button class="btn btn-secondary" type="submit"> <i class="bi bi-trash"></i> remove this question </button>
        </form>

    </div>
    <%
        }
    %>

    <% if(questions.size()!=0){
        DbQuizDAO quizDAO = (DbQuizDAO) request.getServletContext().getAttribute("quizDAO");
        String address = "quizPage.jsp?searchInput="+quizDAO.getQuizByID(Integer.parseInt(quizId)).getQuizName();
    %>
        <a href="<%=address%>"> finish </a>
    <%}%>

</div>
</body>
</html>
