<%
    String[] types = new String[]{"AutoGeneratedQuestion", "FillInTheBlank",
            "Matching","MultiAnswer",
            "MultipleChoice", "MultipleChoiceWithMultipleAnswer",
    "PictureResponse", "QuestionResponse"};
    int total = types.length;
    int index = Integer.parseInt(request.getParameter("index"));
    if (index>=total){
        index%=total;
    }
    out.print("<h1> Question "+(index+1) +"/" + total +"</h1>");
    out.print("<p>" + types[index] + "</p>");

    String type = types[index];
    String path = "questions/" + type + ".jsp";
%>
<jsp:include page="<%= path %>" />

